//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GoodsInfo()
        {
            this.GoodOrder = new HashSet<GoodOrder>();
            this.GoodsImg = new HashSet<GoodsImg>();
        }
    
        public int Id { get; set; }
        public string GoodName { get; set; }
        public Nullable<decimal> GoodPrice { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string Remark { get; set; }
        public Nullable<int> AdderId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodOrder> GoodOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsImg> GoodsImg { get; set; }
        public virtual Sellers Sellers { get; set; }
    }
}
